target_os = "android"
# arm64-v8a 64-bit only architecture target (no 32-bit, no universal)
target_cpu = "arm64"
enable_android_secondary_abi = false

# Android 10 (API level 29) compatibility
default_min_sdk_version = 29

android_channel = "stable"
android_default_version_name = "153.0.8010.52"
android_default_version_code = "801005200"

ext_version_enabled = true
ext_version_increment = "0"

is_component_build = false
is_debug = false
is_official_build = true

# Size optimizations: strip all symbols and debug info, generate resource allowlists
symbol_level = 0
strip_debug_info = true
enable_resource_allowlist_generation = true
use_thin_lto = true

disable_fieldtrial_testing_config = true
dfmify_dev_ui = false

# Restore M125 and older behavior of Password Manager settings,
# which is Play services independent.
use_login_database_as_backend = true

# enable patented codecs
ffmpeg_branding = "Chrome"
proprietary_codecs = true

is_cfi = true
use_cfi_cast = true

enable_vr = false
enable_arcore = false
enable_openxr = false
enable_cardboard = false
enable_remoting = false
enable_reporting = false

trichrome_certdigest = "da378d6a117dca6ecaf39e653efb2d6b686894c4de28ca0792b76565d85a9634"

chrome_public_manifest_package = "app.vanadium.browser"
system_webview_package_name = "app.vanadium.webview"
trichrome_library_package = "app.vanadium.trichromelibrary"

config_apk_package = "app.vanadium.config"
config_apk_certdigest = "da378d6a117dca6ecaf39e653efb2d6b686894c4de28ca0792b76565d85a9634"
config_apk_version_name = "209"
config_apk_version_code = "209"
config_apk_is_debug = false

# Explicitly disable static analysis as intended for official builds.
android_static_analysis = "off"

# Siso aims be a drop-in replacement for Ninja, and to speed up Chromium builds.
use_siso = true

# Enables usage of wasm in jitless mode or interpreter mode via DrumBrake.
v8_enable_drumbrake = true
v8_drumbrake_bounds_checks = true
